name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Node.js 설치
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # 3. .env 파일 값 교체
      - name: Replace environment variables in .env file
        working-directory: frontend
        run: |
          sed -i "s/\${VUE_APP_KAKAOPAY_CID}/${{ secrets.VUE_APP_KAKAOPAY_CID }}/g" .env
          sed -i "s/\${VUE_APP_TOSSPAY_MID}/${{ secrets.VUE_APP_TOSSPAY_MID }}/g" .env
          sed -i "s/\${VUE_APP_PORTONE_STORE_ID}/${{ secrets.VUE_APP_PORTONE_STORE_ID }}/g" .env

      # 4. npm 종속성 설치 및 Vue app 빌드
      - name: Install npm dependencies and build Vue app
        working-directory: frontend
        run: |
          npm install
          npm run build

      # 5. dist 폴더 EC2로 배포
      - name: Deploy dist to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST_FRONT }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY_FRONT }}
          source: frontend/dist/
          target: /var/www/dist/
          strip_components: 2
