name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Node.js 설치
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # 3. npm 종속성 설치 및 Vue app build
      - name: Install npm dependencies and build Vue app
        working-directory: frontend  # frontend 디렉토리로 이동
        run: |
          npm install
          npm run build

      # 4. dist 폴더 EC2로 배포
      - name: Deploy dist to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST_FRONT }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY_FRONT }}
          source: frontend/dist/
          target: /var/www/dist
